// Test plan 16: index.html is generated by tools/build.js (no hand edits) and contains the learning engine.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..');

test('16. tools/build.js regenerates index.html with the engine inlined', () => {
  execFileSync(process.execPath, [path.join(root, 'tools/build.js')], { cwd: root, stdio: 'pipe' });
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  assert.ok(html.startsWith('<!doctype html>'));
  assert.ok(!/<!--LEARNING-ENGINE/.test(html), 'placeholder replaced');
  assert.ok(!html.includes('/*CLIPS*/'), 'audio clips embedded');
  for (const f of ['catalog.js', 'engine.js']) {
    const code = fs.readFileSync(path.join(root, 'src', f), 'utf8');
    assert.ok(html.includes(`<script>\n${code}</script>`), `src/${f} is inlined verbatim`);
  }
  // The engine must load before the app script.
  assert.ok(html.indexOf('root.LearningEngine = factory') < html.indexOf('/* ---------- data ---------- */'));
});
